### ISSUE TITLE
[GSSoC'23] Adding user login with firebase and profile section 

### ISSUE THREAD

**Issue by Aditya-Khaladkar** [Suryansh1720001/Taaveez#43]
### Is your feature request related to a problem? Please describe.

I can't see any user login here and profile section, i can do that with firebase

### Describe the solution you'd like

I can add the userlogin with firebase auth and can add a profile section displaying data of user like username and profile pic, also in the profile section i can add a recyclerview which have fav books marked by user

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ritz-17** [comment]
I beleive we can use appwrite for it for authentication pls assign me the task

**Comment by Suryansh1720001** [comment]
@Aditya-Khaladkar 
The login/signup feature provided by Firebase is not essential for this application. Moreover, if the free tier of Firebase exceeds its limit, it could negatively impact the user experience. Therefore, it is advisable to focus on other areas that require contributions from contributors in order to enhance the app with simple, innovative, and distinctive functionalities.
Also, you can follow me on socials - 
[LinkedIn](https://linkedin.com/in/itssuryansh/)
@Suryansh1720001 
[Twitter](https://twitter.com/itssuryanshP)
